spring:
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    username: ${RABBITMQ_USER:user}
    port: ${RABBITMQ_PORT:5672}
    password: ${RABBITMQ_PASS:password}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 3
        retry:
          enabled: true
          multiplier: 2
    template:
      retry:
        enabled: true
        max-retries: 5
        multiplier: 2
        max-interval: 20000ms
    connection-timeout: 20000
